AWSTemplateFormatVersion: '2010-09-09'
Description: Storage Gateway Backup Bucket

Resources:
  S3BucketForBackup:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 'aws-meetup-storage-gw-backup' 
      AccessControl: 'Private'
      VersioningConfiguration:
        Status: 'Enabled'

  BackupBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        Ref: S3BucketForBackup
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
            Effect: 'Deny'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3BucketForBackup', '/*']]
            Principal: '*'
        #  - 
        #    Action: 
        #      - 's3:DeleteBucket'
        #      - 's3:DeleteBucketPolicy'
        #    Effect: 'Deny'
        #    Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3BucketForBackup']]
        #    Principal: '*'

Outputs:

  S3BucketForBackup:
    Description: 'S3 Bucket Name'
    Value: !Ref 'S3BucketForBackup'